swagger: "2.0"
info:
  title: Door Controller
  description: Simulates a door opening service
  contact:
    name: Tobias Straub
    url: https://tobiasstraub.com
    email: hello@tobiasstraub.com
  version: "0.0.1"
host: localhost:10010
basePath: /api/v1

schemes:
  - http # Remove HTTP in production
  - https
  
consumes:
  - application/json

produces:
  - application/json
  
security:
  - Basic: []
  - OAuth2:
    - read
    
paths:
  /door:
    x-swagger-router-controller: doorSimulator
    get:
      summary: Returns the status of the door
      description: Returns whether the door is open or closed
      operationId: status # used as the method name of the controller
      responses:
        "200":
          description: Executed the 'Door status' command
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error on executing 'Door status' command
          schema:
            $ref: "#/definitions/ErrorResponse"
      security:
        - Basic: []
        - OAuth2:
          - read
          - execute
            
  /door/open:
    x-swagger-router-controller: doorSimulator
    get:
      summary: Opens the door
      description: Simulates an unlock of the door so that it can be opened by the person who is unlocking the door. After successfully executing this endpoint, the door is opened for a time between 3 seconds and 5 minutes.
      # used as the method name of the controller
      operationId: open
      responses:
        "200":
          description: Executed the 'Open door' command
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error on executing 'Open door' command
          schema:
            $ref: "#/definitions/ErrorResponse"
        
securityDefinitions:
  Basic:
    type: basic
    description: Basic authentification can be used for testing with the credentials admin:admin
  OAuth2:
    type: oauth2
    description: OAuth2 authentification
    flow: implicit
    authorizationUrl: http://swagger.io/api/oauth/dialog
    scopes:
      read: Read the status of the door
      execute: Execute door commands
      
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
