swagger: "2.0"
info:
  title: Camera Controller
  description: Service to get the livestream of the camera
  contact:
    name: Tobias Straub
    url: https://tobiasstraub.com
    email: hello@tobiasstraub.com
  version: "0.0.1"
host: localhost:10010
basePath: /api/v1

schemes:
  - http # Remove HTTP in production
  - https

consumes:
  - application/json

produces:
  - application/json

security:
  - Basic: []
  - OAuth2:
    - read

paths:
  /camera:
    x-swagger-router-controller: camera
    get:
      summary: Returns the livestream of the camera
      description: Returns the livestream of the camera
      operationId: livestream # used as the method name of the controller
      responses:
        "200":
          description: Returns the livestream of the camera
          schema:
            $ref: "#/definitions/CameraLivestreamResponse"
        default:
          description: Error on getting the livestream of the camera
          schema:
            $ref: "#/definitions/ErrorResponse"

securityDefinitions:
  Basic:
    type: basic
    description: Basic authentification can be used for testing with the credentials admin:admin
  OAuth2:
    type: oauth2
    description: OAuth2 authentification
    flow: implicit
    authorizationUrl: http://swagger.io/api/oauth/dialog
    scopes:
      read: Get the livestream of the camera

definitions:
  CameraLivestreamResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
